import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Next.js + TailwindCSS</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h3 className="text-4xl text-center font-bold px-2 py-2">
					Next.js + TailwindCSS
				</h3>
			</main>
		</>
	);
}
